title: Climb_and_Dive
description: An Advanced Control Line Timer
theme: just-the-docs
color_scheme: light

logo: "/assets/images/CircuitFlyer.png"

url: https://circuitflyer.com/

aux_links:
  Template Repository: https://github.com/CircuitFlyer/Climb_and_Dive
