title: Climb_and_Dive Instructions
description: An Advanced Control Line Timer
remote_theme: just-the-docs
color_scheme: custom

logo: "/assets/images/CircuitFlyer.png"

url: https://circuitflyer.com/

aux_links:
  Climb_and_Dive on Github: https://github.com/CircuitFlyer/Climb_and_Dive

callouts:
  highlight:
      color: yellow
  warning:
    title: Warning
    color: red
