title: Climb_and_Dive Instructions
description: An Advanced Control Line Timer
theme: just-the-docs
color_scheme: light

logo: "/assets/images/CircuitFlyer.png"

url: https://circuitflyer.com/

aux_links:
  Climb_and_Dive on Github: https://github.com/CircuitFlyer/Climb_and_Dive

callouts:
  highlight:
      color: yellow
